import { Platform, StyleSheet } from 'react-native';

import { getSkeuo } from '@/components/skeuo';
import { Fonts } from '@/lib/fonts';
import type { ThemePalette } from '@/lib/theme';

export function createControllerStyles(theme: ThemePalette) {
  const skeuo = getSkeuo(theme);
  return StyleSheet.create({
    screen: { flex: 1, backgroundColor: theme.bg },
    screenBody: { flex: 1, backgroundColor: theme.bg },
    connectionGate: { flex: 1, backgroundColor: theme.bg },
    connectionGateContent: {
      flexGrow: 1,
      paddingHorizontal: 24,
    },
    gateContent: {
      width: '100%', maxWidth: 430, alignSelf: 'stretch',
    },
    gateContentCentered: {
      flexGrow: 1, alignItems: 'center', justifyContent: 'center', gap: 12, paddingBottom: 80,
    },
    gateHero: {
      marginBottom: 34,
    },
    gateTitle: {
      fontFamily: Fonts.sansBold,
      fontSize: 34,
      lineHeight: 38,
      letterSpacing: -1.1,
      color: theme.text,
    },
    gateTitleMono: {
      marginTop: 2,
      fontFamily: Fonts.mono,
      fontSize: 25,
      lineHeight: 33,
      letterSpacing: 0.2,
      color: theme.textFaint,
    },
    gateNote: {
      marginBottom: 4,
      fontFamily: Fonts.sans,
      fontSize: 14,
      lineHeight: 21,
      color: theme.textMuted,
    },
    gateStateTitle: {
      fontFamily: Fonts.sansSemi,
      fontSize: 17,
      letterSpacing: -0.3,
      color: theme.text,
    },
    gateStateBody: {
      maxWidth: 280,
      textAlign: 'center',
      fontFamily: Fonts.sans,
      fontSize: 13.5,
      lineHeight: 20,
      color: theme.textMuted,
    },
    gateSteps: {
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: theme.divider,
    },
    gateStep: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 14,
      paddingVertical: 20,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: theme.divider,
    },
    gateStepLast: {
      borderBottomWidth: 0,
    },
    gateStepMarker: {
      width: 20,
      paddingTop: 4,
      fontFamily: Fonts.monoMedium,
      fontSize: 11,
      letterSpacing: 0.6,
      color: theme.textFaint,
    },
    gateStepCopy: { flex: 1, minWidth: 0 },
    gateStepTitle: {
      fontFamily: Fonts.sansSemi,
      fontSize: 16,
      lineHeight: 21,
      letterSpacing: -0.2,
      color: theme.text,
    },
    gateStepBody: {
      marginTop: 4,
      maxWidth: 290,
      fontFamily: Fonts.sans,
      fontSize: 13.5,
      lineHeight: 20,
      color: theme.textMuted,
    },
    gateKeyPreview: {
      marginTop: 14,
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 6,
      maxWidth: 208,
    },
    gatePreviewKey: {
      width: 46,
      height: 28,
      borderRadius: 7,
      backgroundColor: theme.surfaceMuted,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.border,
    },
    gatePreviewDial: {
      borderRadius: 14,
      backgroundColor: theme.surface,
    },
    gateCommandRow: {
      marginTop: 14,
      minHeight: 46,
      paddingLeft: 12,
      paddingRight: 6,
      paddingVertical: 6,
      borderRadius: 12,
      backgroundColor: theme.surfaceMuted,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.border,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    gatePrompt: {
      fontFamily: Fonts.mono,
      fontSize: 12.5,
      color: theme.textFaint,
    },
    gateCommandText: {
      flex: 1,
      fontFamily: Fonts.mono,
      fontSize: 12.5,
      color: theme.text,
    },
    gateCopyButton: {
      minWidth: 34,
      height: 34,
      paddingHorizontal: 9,
      borderRadius: 9,
      backgroundColor: theme.surface,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 5,
    },
    gateCopyButtonDone: {
      backgroundColor: theme.mode === 'dark' ? 'rgba(16,163,127,0.22)' : 'rgba(16,163,127,0.12)',
    },
    gateCopyButtonLabel: {
      fontFamily: Fonts.sansSemi,
      fontSize: 12,
      color: theme.online,
    },
    gatePrimaryButton: {
      marginTop: 28,
      height: 50,
      borderRadius: 12,
      backgroundColor: theme.text,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 9,
    },
    gatePrimaryButtonText: {
      fontFamily: Fonts.sansSemi,
      fontSize: 15,
      letterSpacing: -0.2,
      color: theme.bg,
    },
    gateSecondaryButton: {
      marginTop: 10,
      height: 50,
      borderRadius: 12,
      backgroundColor: theme.surface,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.border,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 9,
    },
    gateSecondaryButtonText: {
      fontFamily: Fonts.sansSemi,
      fontSize: 15,
      letterSpacing: -0.2,
      color: theme.text,
    },
    gateDemoButton: {
      alignSelf: 'center',
      minHeight: 44,
      marginTop: 8,
      paddingHorizontal: 14,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 7,
    },
    gateDemoButtonText: {
      fontFamily: Fonts.sansMedium,
      fontSize: 13,
      color: theme.textMuted,
    },
    gateTertiaryButton: {
      height: 44, marginTop: 4, alignItems: 'center', justifyContent: 'center',
    },
    gateTertiaryButtonText: {
      fontFamily: Fonts.sansMedium,
      fontSize: 13,
      color: theme.dangerText,
    },
    gateButtonPressed: { opacity: 0.82, transform: [{ scale: 0.985 }] },
    gateFootnote: {
      marginTop: 16,
      fontFamily: Fonts.sans,
      fontSize: 12.5,
      color: theme.textFaint,
    },
    edgeSwipeZone: {
      position: 'absolute',
      left: 0,
      top: 0,
      bottom: 0,
      width: 32,
      zIndex: 30,
      backgroundColor: 'transparent',
    },
    modalGestureRoot: { flex: 1 },
    ambientBlue: {
      position: 'absolute', width: 430, height: 430, borderRadius: 215, top: 120, left: -20,
      backgroundColor: 'rgba(255,255,255,0.035)',
    },
    ambientGreen: {
      position: 'absolute', width: 360, height: 360, borderRadius: 180, top: 300, left: -200,
      backgroundColor: 'rgba(16,163,127,0.025)',
    },
    scrollContent: {
      flexGrow: 1,
      paddingHorizontal: 16,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 16,
      paddingHorizontal: 2,
      gap: 10,
    },
    headerTitleBlock: { flex: 1, minWidth: 0 },
    headerControls: { flexDirection: 'row', alignItems: 'center', gap: 8, justifyContent: 'flex-end' },
    headerIconButton: {
      width: 40,
      height: 40,
      borderRadius: 20,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.surface,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.border,
    },
    headerStatusDot: {
      position: 'absolute',
      right: 8,
      top: 8,
      width: 7,
      height: 7,
      borderRadius: 4,
      borderWidth: 1.5,
      borderColor: theme.surface,
    },
    eyebrow: {
      fontFamily: Fonts.monoMedium,
      fontSize: 8,
      letterSpacing: 1,
      color: theme.textFaint,
    },
    title: {
      fontFamily: Fonts.sansSemi,
      fontSize: 17,
      lineHeight: 22,
      letterSpacing: -0.4,
      fontWeight: '600',
      color: theme.text,
    },
    iconButton: {
      width: 40, height: 40, borderRadius: 20, alignItems: 'center', justifyContent: 'center',
      backgroundColor: theme.surface, borderWidth: StyleSheet.hairlineWidth, borderColor: theme.border,
    },
    iconButtonPressed: { opacity: 0.72, backgroundColor: theme.surfaceMuted },
    statusButton: {
      width: 40, height: 40, borderRadius: 20, alignItems: 'center', justifyContent: 'center',
      backgroundColor: theme.surface, borderWidth: StyleSheet.hairlineWidth, borderColor: theme.border,
    },
    statusRing: {
      position: 'absolute', width: 18, height: 18, borderRadius: 9, borderWidth: 1.5, opacity: 0.45,
    },
    statusDot: { width: 9, height: 9, borderRadius: 5 },
    threadSwitcher: {
      height: 40,
      borderRadius: 20,
      paddingHorizontal: 12,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      backgroundColor: theme.surface,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.border,
    },
    threadSwitcherDisabled: { opacity: 0.45 },
    threadSwitcherMain: {
      paddingLeft: 10, paddingRight: 8, flexDirection: 'row', alignItems: 'center', gap: 5,
    },
    threadSwitcherNext: {
      width: 30, alignItems: 'center', justifyContent: 'center',
      borderLeftWidth: StyleSheet.hairlineWidth, borderLeftColor: theme.border,
    },
    threadSwitcherPressed: { backgroundColor: theme.surfaceMuted },
    threadSwitcherText: {
      fontSize: 13, fontWeight: '500', letterSpacing: -0.2, color: theme.textMuted,
    },

    deviceGlow: {
      width: '100%',
      maxWidth: 620,
      alignSelf: 'center',
      marginTop: 10,
      marginBottom: 18,
      marginHorizontal: 0,
    },
    device: { aspectRatio: 1377 / 1394 },
    deviceInner: {
      paddingLeft: '11.8%',
      paddingRight: '11.8%',
      paddingTop: '9.5%',
      paddingBottom: '13.8%',
    },
    hardwareArea: { flex: 1, justifyContent: 'flex-start', gap: 5 },
    hardwareOffline: { opacity: 0.5 },
    fourRow: { flexDirection: 'row', justifyContent: 'space-between' },
    bottomRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'stretch' },
    squareSlot: { width: '23.2%', aspectRatio: 1 },
    wideSlot: { width: '48.8%', aspectRatio: 2.1 },
    agentSlotGlyph: {
      fontSize: 13,
      fontWeight: '500',
      color: skeuo.iconMuted,
      opacity: 0.5,
    },
    screwTopLeft: { position: 'absolute', zIndex: 4, left: '7.8%', top: '6.4%' },
    screwTopRight: { position: 'absolute', zIndex: 4, right: '7.8%', top: '6.4%' },
    screwBottomLeft: { position: 'absolute', zIndex: 4, left: '7.8%', bottom: '6.8%' },
    screwBottomRight: { position: 'absolute', zIndex: 4, right: '7.8%', bottom: '6.8%' },
    frameMarkTop: {
      position: 'absolute',
      zIndex: 5,
      top: '4.2%',
      left: 0,
      right: 0,
      textAlign: 'center',
      color: '#111516',
      fontSize: 17,
      fontWeight: '300',
    },
    sideLabelLeftWrap: {
      position: 'absolute',
      left: -92,
      top: '50%',
      marginTop: -9,
      width: 200,
      height: 18,
      alignItems: 'center',
      justifyContent: 'center',
      zIndex: 5,
      transform: [{ rotate: '-90deg' }],
    },
    sideLabelLeft: {
      width: 200,
      textAlign: 'center',
      fontSize: 5.4,
      fontWeight: '500',
      letterSpacing: 0.48,
      color: '#111516',
    },
    sideLabelRightWrap: {
      position: 'absolute',
      right: -92,
      top: '50%',
      marginTop: -9,
      width: 200,
      height: 18,
      alignItems: 'center',
      justifyContent: 'center',
      zIndex: 5,
      transform: [{ rotate: '90deg' }],
    },
    sideLabelRight: {
      width: 200,
      textAlign: 'center',
      fontSize: 5.4,
      fontWeight: '500',
      letterSpacing: 0.6,
      color: '#111516',
    },
    buildLabel: {
      marginTop: 5, textAlign: 'center', fontSize: 6, fontWeight: '600',
      letterSpacing: 0.25, color: '#111516',
    },
    buildLink: {
      marginTop: 6, alignSelf: 'center', flexDirection: 'row', alignItems: 'center', gap: 5,
      paddingVertical: 4, paddingHorizontal: 4,
    },
    buildLinkPressed: { opacity: 0.6 },
    buildLinkText: { fontSize: 7, fontWeight: '800', letterSpacing: 0.9, color: skeuo.accent },
    touchModule: {
      width: '23.2%', aspectRatio: 1, flexDirection: 'row', alignItems: 'center',
      justifyContent: 'center', gap: 5,
    },
    touchPressed: { transform: [{ scale: 0.97 }, { translateY: 1 }] },
    ledStack: { gap: 3.5 },
    miniLed: {
      width: 5.5, height: 4.5, borderRadius: 1, borderWidth: StyleSheet.hairlineWidth,
      borderColor: 'rgba(0,0,0,0.25)',
      shadowColor: skeuo.rgb, shadowOffset: { width: 0, height: 0 },
      shadowRadius: 3, shadowOpacity: 0.6,
    },
    touchRing: {
      width: '56%', aspectRatio: 1, borderRadius: 999, backgroundColor: '#171B1E', borderWidth: 1.5,
      borderColor: '#050708', alignItems: 'center', justifyContent: 'center',
      shadowColor: '#000000', shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3, shadowRadius: 5, elevation: 6, overflow: 'hidden',
    },
    touchRingGlint: {
      position: 'absolute', top: '14%', left: '20%', width: '45%', height: '20%',
      borderRadius: 999, backgroundColor: 'rgba(255,255,255,0.12)',
      transform: [{ rotate: '-24deg' }],
    },
    touchCenter: {
      width: '66%', aspectRatio: 1, borderRadius: 999, backgroundColor: '#050708',
      borderWidth: StyleSheet.hairlineWidth, borderColor: 'rgba(255,255,255,0.06)',
    },

    composerPanel: {
      borderRadius: 24, padding: 16, backgroundColor: theme.surface, borderWidth: 1,
      borderColor: theme.border, marginTop: 18, marginBottom: 8,
      shadowColor: '#000000', shadowOffset: { width: 0, height: 8 },
      shadowOpacity: theme.mode === 'dark' ? 0.3 : 0.04, shadowRadius: 18, elevation: 2,
    },
    composerHeader: {
      flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10,
    },
    composerIdentity: { flex: 1, minWidth: 0, flexDirection: 'row', alignItems: 'center', gap: 10 },
    composerChatIcon: {
      width: 34, height: 34, borderRadius: 12, alignItems: 'center', justifyContent: 'center',
      backgroundColor: theme.surfaceMuted,
    },
    composerIdentityText: { flex: 1, minWidth: 0 },
    composerKicker: {
      fontSize: 11, fontWeight: '500', letterSpacing: -0.1, color: theme.textFaint,
    },
    composerStatusDot: { width: 8, height: 8, borderRadius: 4 },
    composerTitle: {
      marginTop: 1, fontSize: 15, fontWeight: '600', letterSpacing: -0.3, color: theme.text,
    },
    composerStatusTail: { flexDirection: 'row', alignItems: 'center', gap: 6, maxWidth: '38%' },
    composerStatusText: {
      fontSize: 11, fontWeight: '500', letterSpacing: -0.1, textAlign: 'right',
    },
    composerClose: {
      width: 30,
      height: 30,
      borderRadius: 15,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.surfaceMuted,
    },
    composerBox: {
      minHeight: 56, maxHeight: 130, marginTop: 14, borderRadius: 18, paddingLeft: 12,
      paddingRight: 6, paddingVertical: 6, backgroundColor: theme.surfaceInput, borderWidth: 1,
      borderColor: theme.surfaceInputBorder, flexDirection: 'row', alignItems: 'flex-end', gap: 6,
    },
    composerLeadingIcon: { marginBottom: 12, marginLeft: 2 },
    composerInput: {
      flex: 1, minHeight: 42, maxHeight: 114, paddingTop: 10, paddingBottom: 10,
      fontSize: 15, lineHeight: 21, color: theme.text, textAlignVertical: 'top',
    },
    sendButton: {
      width: 40, height: 40, borderRadius: 14, backgroundColor: theme.accent,
      alignItems: 'center', justifyContent: 'center',
    },
    sendButtonDisabled: { backgroundColor: theme.surfaceMuted, opacity: 0.7 },
    sendButtonPressed: { transform: [{ scale: 0.95 }] },
    queueWrap: { marginTop: 12 },
    queueLabel: {
      fontSize: 10, fontWeight: '600', letterSpacing: 0.2, color: theme.textFaint, marginBottom: 4,
    },
    queueRow: {
      minHeight: 36, flexDirection: 'row', alignItems: 'center', gap: 4,
      borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: theme.divider, paddingVertical: 6,
    },
    queueSpinner: { width: 20, alignItems: 'center' },
    queueDotMark: { width: 6, height: 6, borderRadius: 3, marginHorizontal: 7 },
    queueText: { flex: 1, minWidth: 0, fontSize: 13, fontWeight: '500', color: theme.textMuted },
    queueRemove: { width: 28, height: 28, alignItems: 'center', justifyContent: 'center' },
    queueRemoveDisabled: { opacity: 0.4 },
    queueRemovePressed: { opacity: 0.5 },
    composerFooter: {
      marginTop: 12, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
    },
    composerRoute: { flexDirection: 'row', alignItems: 'center', gap: 5 },
    composerMeta: { fontSize: 10, fontWeight: '600', letterSpacing: 0.2, color: theme.textFaint },
    composerNotice: { marginTop: 12 },
    notice: {
      marginTop: 12, borderRadius: 13, paddingHorizontal: 12, paddingVertical: 10,
      backgroundColor: theme.surfaceMuted, flexDirection: 'row', alignItems: 'flex-start', gap: 8,
    },
    noticeError: { backgroundColor: theme.dangerSurface },
    noticeText: { flex: 1, fontSize: 11.5, lineHeight: 16, fontWeight: '700', color: theme.textMuted },
    noticeTextError: { color: theme.dangerText },

    modalBackdrop: { flex: 1, justifyContent: 'flex-end', backgroundColor: theme.scrim },
    sheet: {
      borderTopLeftRadius: 30, borderTopRightRadius: 30, paddingHorizontal: 20, paddingTop: 11,
      backgroundColor: theme.surface, borderTopWidth: 1, borderColor: theme.border,
    },
    settingsSheet: { maxHeight: '88%' },
    consentSheet: { maxHeight: '92%' },
    infoSheet: { maxHeight: '86%' },
    settingsContent: { paddingTop: 4, paddingBottom: 8 },
    catalogSheet: { maxHeight: '92%' },
    keyManagerSheet: { maxHeight: '88%' },
    guideSheet: { maxHeight: '88%' },
    sheetHandle: { width: 42, height: 4, borderRadius: 2, backgroundColor: theme.borderStrong, alignSelf: 'center', marginBottom: 18 },
    sheetTitleRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
    sheetKicker: {
      fontSize: 13, fontWeight: '500', letterSpacing: -0.1, color: theme.textFaint,
    },
    sheetTitle: {
      fontSize: 26, letterSpacing: -0.7, fontWeight: '600', color: theme.text, marginTop: 2,
    },
    closeButton: {
      width: 36, height: 36, borderRadius: 18, backgroundColor: theme.surfaceMuted,
      alignItems: 'center', justifyContent: 'center',
    },
    sheetBody: {
      marginTop: 10, marginBottom: 12, fontSize: 14, lineHeight: 21,
      letterSpacing: -0.15, color: theme.textMuted,
    },
    consentTitleCopy: { flex: 1, paddingRight: 14 },
    consentLead: {
      marginTop: 18, marginBottom: 18, fontFamily: Fonts.sansSemi,
      fontSize: 17, lineHeight: 24, letterSpacing: -0.3, color: theme.text,
    },
    consentPoint: {
      paddingVertical: 14, borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: theme.divider, flexDirection: 'row', alignItems: 'flex-start', gap: 13,
    },
    consentPointNumber: {
      width: 24, paddingTop: 2, fontFamily: Fonts.mono, fontSize: 10,
      letterSpacing: 0.5, color: theme.textFaint,
    },
    consentPointText: {
      flex: 1, fontFamily: Fonts.sans, fontSize: 13.5, lineHeight: 20,
      letterSpacing: -0.1, color: theme.textMuted,
    },
    inlineLink: {
      minHeight: 44, marginTop: 6, paddingVertical: 11,
      flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
    },
    inlineLinkText: {
      fontFamily: Fonts.sansSemi, fontSize: 13.5, color: theme.text,
      textDecorationLine: 'underline',
    },
    consentButtons: {
      paddingTop: 14, flexDirection: 'row', gap: 10,
      borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: theme.divider,
    },
    consentSecondaryButton: {
      flex: 1, height: 50, borderRadius: 14, borderWidth: 1,
      borderColor: theme.borderStrong, alignItems: 'center', justifyContent: 'center',
      backgroundColor: theme.surface,
    },
    consentSecondaryButtonText: {
      fontFamily: Fonts.sansSemi, fontSize: 11, letterSpacing: 0.7, color: theme.textMuted,
    },
    consentDangerButton: {
      flex: 1, height: 50, borderRadius: 14, alignItems: 'center', justifyContent: 'center',
      backgroundColor: theme.dangerSurface, borderWidth: 1, borderColor: theme.danger,
    },
    consentDangerButtonText: {
      fontFamily: Fonts.sansSemi, fontSize: 11, letterSpacing: 0.7, color: theme.dangerText,
    },
    consentPrimaryButton: {
      flex: 1.2, height: 50, borderRadius: 14, alignItems: 'center', justifyContent: 'center',
      flexDirection: 'row', gap: 8, backgroundColor: theme.text,
    },
    consentPrimaryButtonText: {
      fontFamily: Fonts.sansSemi, fontSize: 11, letterSpacing: 0.7, color: theme.bg,
    },
    infoLead: {
      marginTop: 18, fontFamily: Fonts.sansSemi, fontSize: 18,
      lineHeight: 24, letterSpacing: -0.35, color: theme.text,
    },
    infoParagraph: {
      marginTop: 14, fontFamily: Fonts.sans, fontSize: 13.5,
      lineHeight: 21, letterSpacing: -0.12, color: theme.textMuted,
    },
    infoAction: {
      minHeight: 50, marginTop: 22, borderRadius: 14, paddingHorizontal: 16,
      backgroundColor: theme.text, flexDirection: 'row', alignItems: 'center',
      justifyContent: 'center', gap: 9,
    },
    infoActionText: {
      fontFamily: Fonts.sansSemi, fontSize: 11, letterSpacing: 0.65, color: theme.bg,
    },
    infoSecondaryAction: {
      minHeight: 48, marginTop: 10, borderRadius: 14, paddingHorizontal: 15,
      borderWidth: 1, borderColor: theme.borderStrong, flexDirection: 'row',
      alignItems: 'center', justifyContent: 'space-between',
    },
    infoSecondaryActionText: {
      fontFamily: Fonts.sansSemi, fontSize: 11, letterSpacing: 0.55, color: theme.text,
    },
    infoVersion: {
      marginTop: 18, fontFamily: Fonts.mono, fontSize: 10.5,
      lineHeight: 16, letterSpacing: 0.35, color: theme.textFaint,
    },
    cliCommand: {
      minHeight: 48, marginBottom: 14, paddingHorizontal: 14, borderRadius: 14,
      backgroundColor: theme.surfaceInput, borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.border, flexDirection: 'row', alignItems: 'center', gap: 8,
    },
    cliCommandPrompt: { fontSize: 13, fontWeight: '700', color: theme.textFaint },
    cliCommandText: {
      flex: 1, fontSize: 13, fontWeight: '600', color: theme.text,
      fontFamily: Platform.select({ ios: 'Menlo', android: 'monospace' }),
    },

    chatDrawerModal: { flex: 1 },
    chatDrawerScrim: {
      ...StyleSheet.absoluteFillObject, backgroundColor: theme.drawerScrim,
    },
    chatDrawer: {
      position: 'absolute', top: 0, bottom: 0, left: 0, paddingHorizontal: 18,
      backgroundColor: theme.surface, borderTopRightRadius: 28, borderBottomRightRadius: 28,
      borderRightWidth: 1, borderColor: theme.border,
      shadowColor: '#000000', shadowOffset: { width: 12, height: 0 },
      shadowOpacity: 0.28, shadowRadius: 30, elevation: 24,
    },
    chatDrawerHeader: {
      flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
    },
    chatDrawerKicker: {
      fontSize: 8, fontWeight: '900', letterSpacing: 1.15, color: theme.textFaint,
    },
    chatDrawerTitle: {
      marginTop: 3, fontSize: 30, lineHeight: 33, fontWeight: '900',
      letterSpacing: -1.2, color: theme.text,
    },
    chatDrawerClose: {
      width: 40, height: 40, borderRadius: 15, alignItems: 'center', justifyContent: 'center',
      backgroundColor: theme.surfaceMuted, borderWidth: 1, borderColor: theme.border,
    },
    chatDrawerContent: { paddingTop: 20, paddingBottom: 20 },
    chatDrawerSectionText: {
      fontSize: 8, fontWeight: '900', letterSpacing: 1.05, color: theme.textFaint, marginBottom: 8,
    },
    projectGroup: { marginBottom: 18 },
    projectHeader: {
      minHeight: 32, paddingHorizontal: 2,
      flexDirection: 'row', alignItems: 'center', gap: 8,
    },
    projectHeaderPressed: { opacity: 0.6 },
    projectName: {
      flex: 1, fontSize: 13, fontWeight: '900', letterSpacing: -0.2, color: theme.text,
    },
    projectCount: { fontSize: 11, fontWeight: '800', color: theme.textFaint },
    projectThreads: { marginTop: 2 },
    chatRow: {
      minHeight: 54, flexDirection: 'row', alignItems: 'stretch',
      borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: theme.divider,
    },
    chatRowBar: {
      position: 'absolute', left: 0, top: 12, bottom: 12, width: 3, borderRadius: 2,
      backgroundColor: theme.blue,
    },
    chatRowOpen: {
      flex: 1, minWidth: 0, paddingLeft: 14, paddingVertical: 11,
      flexDirection: 'row', alignItems: 'center', gap: 12,
    },
    chatRowPressed: { opacity: 0.55 },
    chatDot: { width: 8, height: 8, borderRadius: 4 },
    chatRowCopy: { flex: 1, minWidth: 0 },
    chatRowName: { fontSize: 13.5, fontWeight: '700', color: theme.textMuted },
    chatRowNameSelected: { fontWeight: '900', color: theme.text },
    chatRowTask: { marginTop: 2, fontSize: 10.5, color: theme.textFaint },
    chatRowArchive: {
      width: 40, alignItems: 'center', justifyContent: 'center',
    },
    chatRowArchivePressed: { opacity: 0.5 },
    chatDrawerFooter: {
      minHeight: 42, paddingTop: 11, flexDirection: 'row', alignItems: 'center',
      justifyContent: 'center', gap: 7, borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: theme.border,
    },
    chatDrawerFooterText: {
      fontSize: 8, fontWeight: '800', letterSpacing: 0.25, color: theme.textFaint,
    },

    inputLabel: {
      fontSize: 13, fontWeight: '500', letterSpacing: -0.1, color: theme.textMuted, marginBottom: 8,
    },
    input: {
      height: 50,
      borderRadius: 14,
      paddingHorizontal: 14,
      marginBottom: 14,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.surfaceInputBorder,
      backgroundColor: theme.surfaceInput,
      color: theme.text,
      fontSize: 15,
      fontWeight: '400',
      letterSpacing: -0.2,
    },
    searchWrap: {
      height: 46, borderRadius: 14, paddingHorizontal: 13, marginBottom: 10, borderWidth: 1,
      borderColor: theme.surfaceInputBorder, backgroundColor: theme.surfaceInput, flexDirection: 'row',
      alignItems: 'center', gap: 8,
    },
    searchInput: { flex: 1, height: '100%', color: theme.text, fontSize: 13, fontWeight: '600' },
    actionCatalog: { paddingBottom: 10 },
    actionRow: {
      minHeight: 58, paddingVertical: 11, flexDirection: 'row', alignItems: 'center', gap: 14,
      borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: theme.divider,
    },
    actionRowPressed: { opacity: 0.55 },
    actionRowIcon: { width: 24, alignItems: 'center', justifyContent: 'center' },
    actionCardPressed: { transform: [{ scale: 0.988 }] },
    actionCopy: { flex: 1, minWidth: 0 },
    actionTitleRow: {
      flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8,
    },
    actionTitle: { flex: 1, fontSize: 13.5, fontWeight: '700', color: theme.textMuted },
    actionTitleSelected: { fontWeight: '900', color: theme.text },
    actionCategory: {
      fontSize: 7, fontWeight: '900', letterSpacing: 0.6, color: theme.textFaint,
      textTransform: 'uppercase',
    },
    actionDescription: { marginTop: 2, fontSize: 10.5, lineHeight: 14, color: theme.textFaint },
    actionCheck: { width: 20, alignItems: 'center' },
    keyManagerGrid: {
      flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between',
      rowGap: 11, paddingBottom: 4,
    },
    keyManagerCard: {
      width: '48.4%', borderRadius: 17, borderWidth: 1, borderColor: theme.border,
      backgroundColor: theme.surfaceInput, overflow: 'hidden',
    },
    keyManagerChoice: { alignItems: 'center', paddingHorizontal: 10, paddingTop: 14, paddingBottom: 10 },
    keyManagerIcon: {
      width: 48, height: 48, borderRadius: 15, backgroundColor: theme.surfaceMuted,
      alignItems: 'center', justifyContent: 'center',
    },
    keyManagerIconEmpty: { backgroundColor: theme.accentSoft, borderWidth: 1, borderColor: theme.accentSoftBorder },
    keyManagerSlot: {
      marginTop: 9, fontSize: 7, fontWeight: '900', letterSpacing: 0.85, color: theme.textFaint,
    },
    keyManagerLabel: {
      width: '100%', marginTop: 3, textAlign: 'center', fontSize: 12,
      fontWeight: '900', color: theme.text,
    },
    removeKeyButton: {
      height: 36, borderTopWidth: 1, borderTopColor: theme.border, backgroundColor: theme.dangerSurface,
      flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 5,
    },
    removeKeyButtonDisabled: { opacity: 0.3 },
    removeKeyButtonPressed: { opacity: 0.8 },
    removeKeyText: { fontSize: 8, fontWeight: '900', letterSpacing: 0.65, color: theme.danger },
    clearAllKeysButton: {
      height: 46, marginTop: 12, borderRadius: 15, borderWidth: 1,
      borderColor: theme.danger, backgroundColor: theme.dangerSurface,
      flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7,
    },
    clearAllKeysButtonDisabled: { opacity: 0.35 },
    clearAllKeysText: {
      fontSize: 9, fontWeight: '900', letterSpacing: 0.75, color: theme.danger,
    },
    customPromptInput: {
      height: 82, paddingTop: 11, textAlignVertical: 'top', marginTop: 2, marginBottom: 8,
    },
    editorButtons: { flexDirection: 'row', gap: 9 },
    clearButton: {
      height: 52, paddingHorizontal: 16, borderRadius: 15, backgroundColor: theme.surfaceMuted,
      flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6,
    },
    clearButtonText: { fontSize: 10, fontWeight: '900', letterSpacing: 0.7, color: theme.textMuted },
    saveKeyButton: {
      flex: 1, height: 52, borderRadius: 15, backgroundColor: theme.accent,
      flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8,
    },
    saveKeyButtonDisabled: { opacity: 0.4 },
    guideContent: { gap: 10, paddingTop: 16, paddingBottom: 6 },
    guideItem: {
      borderRadius: 16, padding: 13, backgroundColor: theme.surfaceInput, borderWidth: 1,
      borderColor: theme.border, flexDirection: 'row', gap: 12,
    },
    guideIcon: {
      width: 42, height: 42, borderRadius: 13, backgroundColor: theme.surfaceMuted,
      alignItems: 'center', justifyContent: 'center',
    },
    guideCopy: { flex: 1 },
    guideTitle: { fontSize: 13, fontWeight: '900', color: theme.text },
    guideBody: { marginTop: 4, fontSize: 11, lineHeight: 15, color: theme.textMuted },
    guideButtonPressed: { opacity: 0.66, transform: [{ scale: 0.98 }] },
    guideSectionIntro: { marginTop: 22, marginBottom: 2 },
    guideSectionTitle: { fontSize: 15, fontWeight: '900', letterSpacing: -0.2, color: theme.text },
    guideSectionBody: { marginTop: 5, fontSize: 11.5, lineHeight: 16, color: theme.textMuted },
    guideGroup: { gap: 10 },
    guideGroupHeading: {
      marginTop: 10, marginBottom: -1, fontSize: 10, fontWeight: '900',
      letterSpacing: 0.8, color: theme.textFaint,
    },
    connectButton: {
      height: 52, borderRadius: 999, marginTop: 6, backgroundColor: theme.accent,
      flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8,
    },
    connectButtonPressed: { opacity: 0.88 },
    connectButtonText: {
      fontSize: 15, fontWeight: '600', letterSpacing: -0.2, color: theme.accentText,
    },
    scanButton: {
      minHeight: 68, borderRadius: 18, marginBottom: 18, paddingHorizontal: 14,
      backgroundColor: theme.surfaceMuted, borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.border,
      flexDirection: 'row', alignItems: 'center', gap: 12,
    },
    scanButtonPressed: { opacity: 0.82 },
    scanButtonIcon: {
      width: 42, height: 42, borderRadius: 21, backgroundColor: theme.accent,
      alignItems: 'center', justifyContent: 'center',
    },
    scanButtonCopy: { flex: 1 },
    scanButtonTitle: {
      fontSize: 15, fontWeight: '600', letterSpacing: -0.2, color: theme.text,
    },
    scanButtonBody: { marginTop: 2, fontSize: 13, color: theme.textFaint },
    manualDivider: {
      marginBottom: 16, flexDirection: 'row', alignItems: 'center', gap: 10,
    },
    manualDividerLine: { flex: 1, height: StyleSheet.hairlineWidth, backgroundColor: theme.border },
    manualDividerText: {
      fontSize: 12, fontWeight: '400', letterSpacing: -0.1, color: theme.textFaint,
    },
    settingsSectionDivider: {
      height: StyleSheet.hairlineWidth, backgroundColor: theme.border, marginTop: 8, marginBottom: 18,
    },
    forgetMacButton: {
      height: 48, marginBottom: 8, borderRadius: 14, backgroundColor: theme.dangerSurface,
      flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8,
    },
    forgetMacButtonText: { fontSize: 14, fontWeight: '700', color: theme.dangerText },
    settingsSpace: { marginTop: 20 },
    settingsGroup: {
      marginBottom: 22,
    },
    settingsGroupLabel: {
      fontFamily: Fonts.sansMedium,
      fontSize: 12,
      letterSpacing: 0.4,
      textTransform: 'uppercase',
      color: theme.textFaint,
      marginBottom: 10,
    },
    settingsSupportingText: {
      marginTop: -3, marginBottom: 7, fontFamily: Fonts.sans,
      fontSize: 12.5, lineHeight: 18, color: theme.textMuted,
    },
    settingsCommandRow: {
      minHeight: 44,
      paddingLeft: 12,
      paddingRight: 6,
      borderRadius: 12,
      backgroundColor: theme.surfaceMuted,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.border,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      marginBottom: 10,
    },
    settingsCommandPrompt: {
      fontFamily: Fonts.mono,
      fontSize: 12.5,
      color: theme.textFaint,
    },
    settingsCommandText: {
      flex: 1,
      fontFamily: Fonts.mono,
      fontSize: 12,
      color: theme.text,
    },
    settingsCopyChip: {
      width: 32,
      height: 32,
      borderRadius: 8,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.surface,
    },
    settingsCopyChipDone: {
      backgroundColor: theme.mode === 'dark' ? 'rgba(16,163,127,0.22)' : 'rgba(16,163,127,0.12)',
    },
    settingsPrimaryButton: {
      height: 46,
      borderRadius: 12,
      backgroundColor: theme.text,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
    },
    settingsPrimaryButtonText: {
      fontFamily: Fonts.sansSemi,
      fontSize: 14.5,
      letterSpacing: -0.2,
      color: theme.bg,
    },
    themeSegment: {
      flexDirection: 'row', gap: 8,
    },
    themeSegmentOption: {
      flex: 1, height: 42, borderRadius: 12, borderWidth: StyleSheet.hairlineWidth, borderColor: theme.border,
      backgroundColor: theme.surfaceInput, flexDirection: 'row', alignItems: 'center',
      justifyContent: 'center', gap: 7,
    },
    themeSegmentOptionActive: { borderColor: theme.text, backgroundColor: theme.surfaceMuted },
    themeSegmentText: { fontFamily: Fonts.sansMedium, fontSize: 13, letterSpacing: -0.1, color: theme.textMuted },
    themeSegmentTextActive: { color: theme.text },
    controllerFieldLabel: {
      marginBottom: 8, fontFamily: Fonts.sansMedium, fontSize: 12, color: theme.textMuted,
    },
    encoderModeSegment: {
      flexDirection: 'row', gap: 6, marginBottom: 10,
    },
    encoderModeOption: {
      flex: 1, height: 38, borderRadius: 11, borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.border, backgroundColor: theme.surfaceInput,
      alignItems: 'center', justifyContent: 'center',
    },
    encoderModeOptionActive: {
      borderColor: theme.text, backgroundColor: theme.surfaceMuted,
    },
    encoderModeText: {
      fontFamily: Fonts.sansMedium, fontSize: 11.5, color: theme.textMuted,
    },
    encoderModeTextActive: { color: theme.text },
    settingsLinkRow: {
      minHeight: 48,
      paddingVertical: 12,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: theme.divider,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
    },
    settingsLinkRowPressed: { opacity: 0.55 },
    settingsLinkTitle: {
      fontFamily: Fonts.sansSemi,
      fontSize: 15,
      letterSpacing: -0.2,
      color: theme.text,
    },
    settingsLinkMeta: {
      marginTop: 3, fontFamily: Fonts.sans, fontSize: 11.5, color: theme.textFaint,
    },
    consentStatusDot: { width: 8, height: 8, borderRadius: 4 },
    settingsDangerLink: {
      marginTop: 4,
      height: 44,
      alignItems: 'center',
      justifyContent: 'center',
    },
    settingsDangerLinkText: {
      fontFamily: Fonts.sansMedium,
      fontSize: 14,
      color: theme.dangerText,
    },
    settingsRow: {
      minHeight: 56, borderRadius: 16, paddingHorizontal: 14, marginTop: 8,
      flexDirection: 'row', alignItems: 'center', gap: 12,
      backgroundColor: theme.surfaceMuted, borderWidth: StyleSheet.hairlineWidth, borderColor: theme.border,
    },
    settingsRowPressed: { backgroundColor: theme.surfaceMuted },
    settingsRowIcon: {
      width: 38, height: 38, borderRadius: 12, alignItems: 'center', justifyContent: 'center',
      backgroundColor: theme.surfaceMuted,
    },
    settingsRowCopy: { flex: 1 },
    settingsRowTitle: { fontSize: 13, fontWeight: '900', color: theme.text },
    settingsRowBody: { marginTop: 2, fontSize: 10.5, lineHeight: 14, color: theme.textMuted },

    scannerScreen: { flex: 1, backgroundColor: '#071014' },
    scannerHeader: {
      position: 'absolute', top: 0, left: 0, right: 0, paddingHorizontal: 18,
      paddingBottom: 16, flexDirection: 'row', alignItems: 'center',
      justifyContent: 'space-between', backgroundColor: 'rgba(4,12,15,0.58)',
    },
    scannerClose: {
      width: 42, height: 42, borderRadius: 21, alignItems: 'center', justifyContent: 'center',
      backgroundColor: 'rgba(255,255,255,0.16)',
    },
    scannerTitle: { fontSize: 16, fontWeight: '900', color: '#FFFFFF' },
    scannerHeaderSpacer: { width: 42 },
    scannerFrame: {
      position: 'absolute', width: 252, height: 252, left: '50%', top: '50%',
      marginLeft: -126, marginTop: -126,
    },
    scannerCorner: { position: 'absolute', width: 42, height: 42, borderColor: theme.blue },
    scannerCornerTopLeft: { top: 0, left: 0, borderTopWidth: 5, borderLeftWidth: 5, borderTopLeftRadius: 16 },
    scannerCornerTopRight: { top: 0, right: 0, borderTopWidth: 5, borderRightWidth: 5, borderTopRightRadius: 16 },
    scannerCornerBottomLeft: { bottom: 0, left: 0, borderBottomWidth: 5, borderLeftWidth: 5, borderBottomLeftRadius: 16 },
    scannerCornerBottomRight: { bottom: 0, right: 0, borderBottomWidth: 5, borderRightWidth: 5, borderBottomRightRadius: 16 },
    scannerFooter: {
      position: 'absolute', left: 0, right: 0, bottom: 0, paddingHorizontal: 32,
      paddingTop: 22, backgroundColor: 'rgba(4,12,15,0.68)',
    },
    scannerHint: { fontSize: 13, lineHeight: 19, fontWeight: '700', color: '#FFFFFF', textAlign: 'center' },
  });
}

export type ControllerStyles = ReturnType<typeof createControllerStyles>;
