import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import test from 'node:test';

const serverSource = await readFile(new URL('../server.mjs', import.meta.url), 'utf8');
const pairingSource = await readFile(
  new URL('../../mobile/lib/pairing.ts', import.meta.url),
  'utf8',
);
const controllerSource = await readFile(
  new URL('../../mobile/app/index.tsx', import.meta.url),
  'utf8',
);

test('a custom scheme needs three slashes to carry a routable path', () => {
  // The reason for the fix, as a live check rather than a comment: with two
  // slashes the segment is parsed as the host and the path comes out empty, so
  // Expo Router has nothing to match and opens "Unmatched Route".
  const twoSlashes = new URL('microdex://pair');
  assert.equal(twoSlashes.host, 'pair');
  assert.equal(twoSlashes.pathname, '');

  const threeSlashes = new URL('microdex:///pair');
  assert.equal(threeSlashes.host, '');
  assert.equal(threeSlashes.pathname, '/pair');
});

test('both the bridge and the app build the routable form', () => {
  assert.match(serverSource, /new URL\('microdex:\/\/\/pair'\)/);
  assert.match(pairingSource, /new URL\('microdex:\/\/\/pair'\)/);
  assert.doesNotMatch(serverSource, /new URL\('microdex:\/\/pair'\)/);
  assert.doesNotMatch(pairingSource, /new URL\('microdex:\/\/pair'\)/);
});

test('the app still accepts links generated by an older bridge', () => {
  // The guard has to tolerate both slash forms, because a bridge that was not
  // updated keeps emitting the two-slash link.
  assert.match(
    controllerSource,
    /const isPairDeepLink = \/\^microdex:\\\/\\\/\\\/\?pair\\b\/\.test\(incomingUrl\)/,
  );

  const pattern = /^microdex:\/\/\/?pair\b/;
  for (const url of [
    'microdex://pair?url=http%3A%2F%2F10.0.0.2%3A3210&code=ABC',
    'microdex:///pair?url=http%3A%2F%2F10.0.0.2%3A3210&code=ABC',
  ]) {
    assert.ok(pattern.test(url), `${url} should be recognized`);
  }
  // A different deep link must not be mistaken for pairing.
  assert.ok(!pattern.test('microdex:///settings?x=1'));
  assert.ok(!pattern.test('microdex:///pairing-help'));
});

test('an unmatched deep link recovers instead of dead-ending', async () => {
  const notFound = await readFile(
    new URL('../../mobile/app/+not-found.tsx', import.meta.url),
    'utf8',
  );
  assert.match(notFound, /Redirect href="\/"/);
});

test('the pairing page keeps working for phones without the app', () => {
  // The QR encodes the http form, which a camera can open; only the button uses
  // the deep link. Losing the http form would break first-time pairing.
  assert.match(serverSource, /url\.pathname === '\/pair'/);
  assert.match(pairingSource, /export function buildPairingHttpUrl/);
});
