import {
  IconAdjustments,
  IconAdjustmentsDown,
  IconAlertCircle,
  IconArchive,
  IconArrowLeft,
  IconArrowRight,
  IconArrowUp,
  IconArrowUpRight,
  IconArrowsDiff,
  IconBackspace,
  IconBolt,
  IconBook2,
  IconBox,
  IconBrain,
  IconBrowser,
  IconBug,
  IconCheck,
  IconChevronDown,
  IconChevronRight,
  IconChevronUp,
  IconCircle,
  IconCircleCheck,
  IconCirclePlus,
  IconCircleX,
  IconClipboardCheck,
  IconClipboardText,
  IconClock,
  IconCloudUpload,
  IconConfetti,
  IconCopy,
  IconDownload,
  IconDeviceGamepad2,
  IconFlask,
  IconFolder,
  IconFolderOpen,
  IconFolderPlus,
  IconFolders,
  IconFolderX,
  IconGitBranch,
  IconGitCommit,
  IconGitFork,
  IconGitMerge,
  IconGitPullRequest,
  IconGitPullRequestDraft,
  IconGridDots,
  IconHierarchy2,
  IconKeyboard,
  IconLayoutBottombar,
  IconLayoutSidebarLeftExpand,
  IconLink,
  IconLogout,
  IconMenu2,
  IconMessageCircle,
  IconMessagePlus,
  IconMicrophone,
  IconMoon,
  IconPalette,
  IconPaperclip,
  IconPin,
  IconPlayerPlay,
  IconPlus,
  IconPointer,
  IconPuzzle,
  IconQrcode,
  IconRefresh,
  IconRocket,
  IconSearch,
  IconSend,
  IconSettings,
  IconSparkles,
  IconSquare,
  IconSquarePlus,
  IconSun,
  IconTerminal2,
  IconTag,
  IconTrash,
  IconWaveSine,
  IconX,
} from '@tabler/icons-react-native';
import type { ComponentProps } from 'react';

/**
 * Microdex uses one redistributable icon family throughout the app. The legacy
 * Material icon names remain as internal aliases so saved layouts and action
 * metadata do not need a migration.
 */
const MICRODEX_ICONS = {
  skillsBlock: IconBox,
  sidebarPanel: IconLayoutSidebarLeftExpand,
  gitCommit: IconGitCommit,
  reviewPanel: IconClipboardCheck,
  bottomPanel: IconLayoutBottombar,
  archive: IconArchive,
  arrowLeft: IconArrowLeft,
  arrowUp: IconArrowUp,
  refresh: IconRefresh,
  link: IconLink,
  chat: IconMessageCircle,
  successCircle: IconCircleCheck,
  check: IconCheck,
  chevronDown: IconChevronDown,
  chevronRight: IconChevronRight,
  output: IconPointer,
  close: IconX,
  alert: IconAlertCircle,
  copy: IconCopy,
  folder: IconFolder,
  folderRemove: IconFolderX,
  folderOpen: IconFolderOpen,
  search: IconSearch,
  moon: IconMoon,
  plus: IconPlus,
  qrCode: IconQrcode,
  settings: IconSettings,
  sun: IconSun,
  trash: IconTrash,
  'arrow-decision-outline': IconGitBranch,
  'arrow-top-right-thick': IconArrowUpRight,
  blur: IconBook2,
  brain: IconBrain,
  'bug-outline': IconBug,
  'call-split': IconGitFork,
  'check-circle-outline': IconCircleCheck,
  'checkbox-blank-outline': IconSquare,
  'clock-outline': IconClock,
  'close-circle-outline': IconCircleX,
  'cloud-upload-outline': IconCloudUpload,
  'cog-outline': IconSettings,
  console: IconTerminal2,
  'cursor-default-click-outline': IconPointer,
  'dots-grid': IconGridDots,
  'flask-outline': IconFlask,
  'folder-plus-outline': IconFolderPlus,
  'format-paint': IconPalette,
  'head-cog-outline': IconAdjustmentsDown,
  'lightning-bolt-outline': IconBolt,
  'microphone-outline': IconMicrophone,
  'party-popper': IconConfetti,
  'play-circle-outline': IconPlayerPlay,
  'plus-box-outline': IconSquarePlus,
  'plus-minus-variant': IconArrowsDiff,
  'robot-outline': IconSend,
  'rocket-launch-outline': IconRocket,
  'source-branch': IconGitBranch,
  'source-branch-plus': IconGitPullRequestDraft,
  'source-merge': IconGitMerge,
  'source-pull': IconGitPullRequest,
  'star-four-points-outline': IconSparkles,
  'trash-can-outline': IconTrash,
  'tray-arrow-down': IconDownload,
  'archive-outline': IconArchive,
  'arrow-left': IconArrowLeft,
  'arrow-right': IconArrowRight,
  'backspace-outline': IconBackspace,
  'book-open-page-variant-outline': IconBook2,
  'chevron-down': IconChevronDown,
  'chevron-up': IconChevronUp,
  'clipboard-check-outline': IconClipboardCheck,
  'clipboard-text-outline': IconClipboardText,
  'content-copy': IconCopy,
  'dock-bottom': IconLayoutBottombar,
  'file-tree': IconHierarchy2,
  'folder-swap-outline': IconFolders,
  'keyboard-outline': IconKeyboard,
  magnify: IconSearch,
  menu: IconMenu2,
  'message-plus-outline': IconMessagePlus,
  'page-layout-sidebar-left': IconLayoutSidebarLeftExpand,
  paperclip: IconPaperclip,
  'pin-outline': IconPin,
  'plus-circle-outline': IconCirclePlus,
  'puzzle-outline': IconPuzzle,
  'source-commit': IconGitCommit,
  'tune-variant': IconAdjustments,
  web: IconBrowser,
  'play-outline': IconPlayerPlay,
  'exit-to-app': IconLogout,
  'circle-outline': IconCircle,
  'voice-wave': IconWaveSine,
  'gamepad-round-outline': IconDeviceGamepad2,
  waveform: IconWaveSine,
  'label-outline': IconTag,
} as const;

export type MicrodexIconName = keyof typeof MICRODEX_ICONS;

type MicrodexIconProps = {
  name: MicrodexIconName;
  size?: number;
  color?: string;
  strokeWidth?: number;
  style?: ComponentProps<typeof IconCircle>['style'];
};

export function MicrodexIcon({
  name,
  size = 24,
  color = '#111719',
  strokeWidth = 1.8,
  style,
}: MicrodexIconProps) {
  const Icon = MICRODEX_ICONS[name];
  return (
    <Icon
      size={size}
      color={color}
      strokeWidth={strokeWidth}
      style={style}
    />
  );
}
